<?php
$arSectionsUrl = [
    "Сухие смеси" => [
        "Универсальные сухие смеси" => "https://www.isolux.ru/stroymateriali/suhie-smesi-1/universalnyye-smesi.html",
        "Затирка для плитки" => "https://www.isolux.ru/stroymateriali/suhie-smesi-1/zatirka-dlya-plitki.html",
        "Гидроизоляция" => "https://www.isolux.ru/stroymateriali/gidroizolyatsiya/gidroizolyacionnie-smesi.html",
        "Кладочные растворы" => "https://www.isolux.ru/stroymateriali/suhie-smesi-1/kladochnyye-i-montazhnyye-smesi.html",
    ],
    "Лакокрасочная продукция" => [
        "Колеры и тонеры" => "https://www.isolux.ru/otdelochnie-materiali/lakokrasochnye-materialy/koleri-i-toneri.html",
        "Эмали" => "https://www.isolux.ru/otdelochnie-materiali/lakokrasochnye-materialy/emali.html",
        "Антисептики" => "https://www.isolux.ru/antiseptik-dlya-gipsokartona",
        "Олифа" => "https://www.isolux.ru/otdelochnie-materiali/lakokrasochnye-materialy/rastvoriteli-i-ochistiteli/olifa.html",
        "Морилки и пропитки" => "https://www.isolux.ru/otdelochnie-materiali/lakokrasochnye-materialy/morilki-i-propitki.html",
    ],
    "Гипсокартонные системы" => [
        "Аквапанели" => [
            "Для наружных работ" => "https://www.isolux.ru/akvapaneli-knauf-dlya-naruzhnyh-rabot",
            "Для ванной комнаты" => "https://www.isolux.ru/akvapaneli-knauf-dlya-vannoj",
            "Для пола" => "https://www.isolux.ru/akvapaneli-knauf-dlya-pola",
            "Для внутренней отделки" => "https://www.isolux.ru/akvapaneli-knauf-dlya-vnutrennih-rabot",
            "12,5 мм" => "https://www.isolux.ru/akvapaneli-knauf-12-5-mm",
            "8 мм" => "https://www.isolux.ru/akvapaneli-knauf-8-mm",
            "6 мм" => "https://www.isolux.ru/akvapaneli-knauf-6-mm",
        ],
        "Крепеж для профиля гипсокартона" => [
            "Подвесы" => "https://www.isolux.ru/podvesy-dlya-gipsokartona",
            "Соединители профилей" => "https://www.isolux.ru/soediniteli-profiley",
            "Удлинители профиля" => "https://www.isolux.ru/udliniteli-profiley",
            "Тяга" => "https://www.isolux.ru/tyaga-dlya-profilya-gipsokartona",
        ],
        "Строительные ленты" => "https://www.isolux.ru/stroymateriali/gipsokarton/lenti-stroitelnie.html",
//        "Гипсокартон",
//        "Гипсоволокно",
//        "Пазогребневые плиты",
//        "Профиль для гипсокартона",
    ],
    "Звукоизоляция" => [
        "Звукоизоляционные материалы" => [
            "Звукоизоляционные панели" => "https://www.isolux.ru/stroymateriali/zvukoizolyatsiya/zvukoizolyatsionnyye-materialy/zvukoizolyatsionnyye-paneli.html",
            "Звукоизоляционные мембраны" => "https://www.isolux.ru/stroymateriali/zvukoizolyatsiya/zvukoizolyatsionnyye-materialy/zvukoizolyatsionnyye-membrany.html",
            "Акустические стеновые панели" => "https://www.isolux.ru/stroymateriali/zvukoizolyatsiya/zvukoizolyatsionnyye-materialy/akusticheskiye-stenovyye-paneli.html",
        ],
        "Шумопоглощающие материалы" => [
            "Шумопоглощающие плиты" => "https://www.isolux.ru/stroymateriali/zvukoizolyatsiya/shumopoglashchayushchiye-materialy-1/shumopoglashchayushchiye-plity.html",
            "Шумопоглощающие маты" => "https://www.isolux.ru/stroymateriali/zvukoizolyatsiya/shumopoglashchayushchiye-materialy-1/shumopoglashchayushchiye-maty.html",
            "Шумопоглощающие панели" => "https://www.isolux.ru/stroymateriali/zvukoizolyatsiya/shumopoglashchayushchiye-materialy-1/shumopoglashchayushchiye-paneli.html",
        ],
        "Вибродемпфирующие материалы" => [
            "Вибродемпфирующие маты" => "https://www.isolux.ru/stroymateriali/zvukoizolyatsiya/vibrodempferiruyushchiye-materialy/vibrodempferiruyushchiye-maty.html",
            "Вибродемпфирующие подложки, полотна" => "https://www.isolux.ru/stroymateriali/zvukoizolyatsiya/vibrodempferiruyushchiye-materialy/vibrodempferiruyushchiye-podlozhki-polotna.html",
        ],
    ],
    "Крепеж" => [
        "Саморезы" => "https://www.isolux.ru/samorezi-dlya-gipsokartona",
        "Шурупы" => "https://www.isolux.ru/stroymateriali/krepezh-1/shurupi.html?attribute_2185_22=18618",
        "Перфорированный крепеж" => "https://www.isolux.ru/stroymateriali/krepezh-1/perforirovannyy-krepezh.html",
    ],
    "Керамогранит" => [
        "Для улицы" => "https://www.isolux.ru/keramogranit-dlja-ulicy",
        "Для кухни" => "https://www.isolux.ru/keramogranit-dlya-kuhni",
        "Для ванной" => "https://www.isolux.ru/keramogranit-dlya-vannoj-komnaty",
        "Для гаража" => "https://www.isolux.ru/keramogranit-dlya-garazha-na-pol",
        "Для гостиной" => "https://www.isolux.ru/keramogranit-dlya-gostinoj",
        "Для коридора" => "https://www.isolux.ru/keramogranit-dlya-koridora",
        "Для общественных помещений" => "https://www.isolux.ru/keramogranit-dlya-obshchestvennyh-pomeshchenij",
        "Для офиса" => "https://www.isolux.ru/keramogranit-dlya-ofisa",
        "Для террасы" => "https://www.isolux.ru/keramogranit-dlya-terrasy",
        "Для производственных помещений" => "https://www.isolux.ru/keramogranit-dlya-proizvodstvennyh-pomeshchenij",
        "Для санузла" => "https://www.isolux.ru/keramogranit-dlya-sanuzla",
        "Для торговых центров" => "https://www.isolux.ru/keramogranit-dlya-torgovyh-centrov",
        "Керамогранит для пола" => "https://www.isolux.ru/keramogranit-dlja-pola",
        "Керамогранит для фасада" => "https://www.isolux.ru/keramogranit-fasadnyj",
        "Керамогранит для стен" => "https://www.isolux.ru/keramogranit-dlja-sten",
        "Керамогранит на фартук" => "https://www.isolux.ru/keramogranit-dlya-kuhni-na-fartuk",
        "Глянцевый" => "https://www.isolux.ru/keramogranit-polirovanniy",
        "Неполированный" => "https://www.isolux.ru/keramogranit-nepolirovanniy",
        "Матовый" => "https://www.isolux.ru/keramogranit-matoviy",
        "Глазурованный" => "https://www.isolux.ru/keramogranit-glazurovannyj",
        "Рельефный" => "https://www.isolux.ru/keramogranit-relefnyj",
        "Структурированный" => "https://www.isolux.ru/keramogranit-strukturirovannyj",
        "Гладкий" => "https://www.isolux.ru/keramogranit-gladkij",
    ],
    "Ручной инструмент" => [
        "Кисти" => "https://www.isolux.ru/instrument-i-oborudovaniye/ruchnoy-instrument/malyarnyy-instrument/kisti.html",
        "Валики" => "https://www.isolux.ru/instrument-i-oborudovaniye/ruchnoy-instrument/malyarnyy-instrument/valiki-1.html",
        "Шпателя" => "https://www.isolux.ru/instrument-i-oborudovaniye/ruchnoy-instrument/shtukaturnyy-instrument/shpateli.html",
        "Ножовки и пилы" => "https://www.isolux.ru/instrument-i-oborudovaniye/ruchnoy-instrument/stolyarno-slesarniy-instrument/nozhovki.html",
        "Рубанки" => "https://www.isolux.ru/instrument-i-oborudovaniye/ruchnoy-instrument/stolyarno-slesarniy-instrument/rubanki.html",
        "Стамески" => "https://www.isolux.ru/instrument-i-oborudovaniye/ruchnoy-instrument/stolyarno-slesarniy-instrument/stameski.html",
        "Молотки" => "https://www.isolux.ru/instrument-i-oborudovaniye/ruchnoy-instrument/udarno-richazhnoy-instrument/molotki.html",
        "Кувалды" => "https://www.isolux.ru/instrument-i-oborudovaniye/ruchnoy-instrument/udarno-richazhnoy-instrument/kuvaldi.html",
        "Киянки" => "https://www.isolux.ru/instrument-i-oborudovaniye/ruchnoy-instrument/udarno-richazhnoy-instrument/kiyanki.html",
        "Губцевый инструмент" => "https://www.isolux.ru/instrument-i-oborudovaniye/ruchnoy-instrument/ploskogubtsy-i-passatizhi.html",
        "Отвертки" => "https://www.isolux.ru/instrument-i-oborudovaniye/ruchnoy-instrument/otvertki/krestovie-otvertki.html",
        "Биты" => "https://www.isolux.ru/instrument-i-oborudovaniye/ruchnoy-instrument/otvertki/otvertki-dlya-bit-biti.html",
        "Ключи" => "https://www.isolux.ru/instrument-i-oborudovaniye/ruchnoy-instrument/klyuchi-gaechnyye.html",
        "Сверла по металлу" => "https://www.isolux.ru/instrument-i-oborudovaniye/raskhodnyye-materialy-1/sverla.html",
        "Буры" => "https://www.isolux.ru/instrument-i-oborudovaniye/raskhodnyye-materialy-1/buri.html",
    ],
    "Измерительный инструмент" => [
        "Линейки" => "https://www.isolux.ru/instrument-i-oborudovaniye/ruchnoy-instrument/izmeritelnyy-instrument/lineyki.html",
        "Рулетки" => "https://www.isolux.ru/instrument-i-oborudovaniye/ruchnoy-instrument/izmeritelnyy-instrument/ruletki.html",
        "Строительные уровни" => "https://www.isolux.ru/instrument-i-oborudovaniye/ruchnoy-instrument/izmeritelnyy-instrument/urovni.html",
    ],
    "Пена и герметики" => [
        "Пена монтажная" => "https://www.isolux.ru/stroymateriali/peny-germetiki-klei/peny-montazhnye.html",
        "Герметики" => "https://www.isolux.ru/stroymateriali/peny-germetiki-klei/germetiki.html",
        "Очистители" => "https://www.isolux.ru/stroymateriali/peny-germetiki-klei/ochistiteli.html",
    ],
];